## Participation

## Convolution Code

In [1]:
import numpy as np

In [2]:
myimg = [[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,1]]
myimg

[[30, 30, 30, 0, 0, 0],
 [30, 30, 30, 0, 0, 0],
 [30, 30, 30, 0, 0, 0],
 [30, 30, 30, 0, 0, 0],
 [30, 30, 30, 0, 0, 0],
 [30, 30, 30, 0, 0, 1]]

In [3]:
myimg = np.array(myimg)
myimg

array([[30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  1]])

In [4]:
myimg[0]

array([30, 30, 30,  0,  0,  0])

In [5]:
myimg[:,0]

array([30, 30, 30, 30, 30, 30])

In [6]:
myimg[:3]

array([[30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0]])

In [7]:
myimg[:3,:]

array([[30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0]])

In [8]:
myimg[:,:3]

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30],
       [30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [9]:
my3x3 = myimg[:3,:3]
my3x3

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [10]:
myvertedge = np.array([[-1, 0, 1],[-1, 0, 1],[-1, 0, 1]])
myvertedge

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [11]:
my3x3[:,0]

array([30, 30, 30])

In [13]:
myvertedge[:,0]

array([-1, -1, -1])

In [14]:
my3x3[:,0] @ myvertedge[:,0]

-90

In [15]:
my3x3[:,1]

array([30, 30, 30])

In [16]:
myvertedge[:,1]

array([0, 0, 0])

In [17]:
my3x3[:,1] @ myvertedge[:,1]

0

In [18]:
myvertedge[:,2]

array([1, 1, 1])

In [19]:
my3x3[:,2] @ myvertedge[:,2]

90

In [20]:
my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]

0

In [21]:
my3x3 = myimg[1:4,1:4]
my3x3

array([[30, 30,  0],
       [30, 30,  0],
       [30, 30,  0]])

In [22]:
my3x3[:,0] @ myvertedge[:,0]

-90

In [23]:
my3x3[:,1] @ myvertedge[:,1]

0

In [24]:
my3x3[:,2] @ myvertedge[:,2]

0

In [25]:
my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]

-90

In [26]:
my3x3 = myimg[2:5,2:5]
my3x3

array([[30,  0,  0],
       [30,  0,  0],
       [30,  0,  0]])

In [27]:
my3x3[:,0] @ myvertedge[:,0]

-90

In [28]:
my3x3[:,1] @ myvertedge[:,1]

0

In [29]:
my3x3[:,2] @ myvertedge[:,2]

0

In [30]:
my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]

-90

In [31]:
myimg.shape

(6, 6)

In [32]:
myvertedge.shape

(3, 3)

In [33]:
np.array(myimg.shape)

array([6, 6])

In [34]:
np.array(myimg.shape) - np.array(myvertedge.shape)

array([3, 3])

In [35]:
myimg = np.array([[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,0],[30,30,30,0,0,1]])
myimg

array([[30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  0],
       [30, 30, 30,  0,  0,  1]])

In [36]:
my3x3 = myimg[3:6,0:3]
my3x3

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [37]:
def myconv2d(X,convKernel):
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen):
    for i in range(0,xlen):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      print(my3x3)

In [38]:
myconv2d(myimg, myvertedge)

[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[0]
 [0]
 [0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[0]
 [0]
 [0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[0]
 [0]
 [0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0]
 [0 0]
 [0 1]]
[[0]
 [0]
 [1]]
[[30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 1]]
[[0 0]
 [0 1]]
[[0]
 [1]]
[[30 30 30]]
[[30 30  0]]
[[30  0  0]]
[[0 0 1]]
[[0 1]]
[[1]]


In [40]:
def myconv2d(X,convKernel):
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen):
    for i in range(0,xlen-convklen+1):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      print(my3x3)

In [41]:
myconv2d(myimg, myvertedge)

[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 1]]
[[30 30 30]]
[[30 30  0]]
[[30  0  0]]
[[0 0 1]]


In [42]:
def myconv2d(X,convKernel):
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen-convklen+1):
    for i in range(0,xlen-convklen+1):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      print(my3x3)

In [43]:
myconv2d(myimg, myvertedge)

[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30  0]
 [30 30  0]
 [30 30  0]]
[[30  0  0]
 [30  0  0]
 [30  0  0]]
[[0 0 0]
 [0 0 0]
 [0 0 1]]


In [44]:
def myconv2d(X,convKernel):
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen-convklen+1):
    for i in range(0,xlen-convklen+1):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      convtransform = my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]
      print(convtransform)

In [45]:
myconv2d(myimg, myvertedge)

0
-90
-90
0
0
-90
-90
0
0
-90
-90
0
0
-90
-90
1


In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
def myconv2d(X,convKernel):
  myconv2dtransformimg = np.zeros((4,4))
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen-convklen+1):
    for i in range(0,xlen-convklen+1):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      convtransform = my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]
      myconv2dtransformimg[j,i] = convtransform
      print(myconv2dtransformimg)

In [47]:
myconv2d(myimg, myvertedge)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[  0. -90.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0. -90.   0.   0.]
 [  0.   0.   0.   0.]]
[[  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0. -90. -90.   0.]
 [  0.   0.   0.   0.]]
[[  0. -9

In [48]:
def myconv2d(X,convKernel):
  myconv2dtransformimg = np.zeros((4,4))
  xlen = myimg.shape[1]
  ylen = myimg.shape[0]
  convklen = convKernel.shape[0]
  for j in range(0,ylen-convklen+1):
    for i in range(0,xlen-convklen+1):
      my3x3 = myimg[j:j+convklen,i:i+convklen]
      convtransform = my3x3[:,0] @ myvertedge[:,0] + my3x3[:,1] @ myvertedge[:,1] + my3x3[:,2] @ myvertedge[:,2]
      myconv2dtransformimg[j,i] = convtransform
  #print(myconv2dtransformimg)
  return myconv2dtransformimg

In [49]:
myconv2d(myimg, myvertedge)

array([[  0., -90., -90.,   0.],
       [  0., -90., -90.,   0.],
       [  0., -90., -90.,   0.],
       [  0., -90., -90.,   1.]])